package com.github.nekit508.nmp.tasks.core

import com.github.nekit508.nmp.extensions.NMPluginCoreExtension
import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import org.gradle.work.DisableCachingByDefault

import javax.inject.Inject
import java.util.concurrent.atomic.AtomicLong
import java.util.regex.Pattern

@DisableCachingByDefault(because = "I dont know can it be cached.")
class BundlesAutoGen extends DefaultTask {
    @Internal
    NMPluginCoreExtension ext

    @Internal
    final Property<Boolean> trace

    @Internal
    var blockPattern = Pattern.compile "[\"']@([\\w_-]+)*?[\"']\\s*?/\\*.*?\\*/", Pattern.DOTALL

    @Internal
    var pairPattern = Pattern.compile "(\\w+):\\s*?\"([^\"]*)\""

    @InputFiles
    final ConfigurableFileCollection files

    @InputFiles
    final ConfigurableFileCollection originalFiles

    @Input
    final Property<String> autoGeneratedNamesPrefix

    @OutputDirectory
    final Property<File> bundlesDir

    @Inject
    BundlesAutoGen(NMPluginCoreExtension ext) {
        group = "nmp"
        this.ext = ext

        var factory = getProject().getObjects()

        files = factory.fileCollection()
        originalFiles = factory.fileCollection()

        bundlesDir = factory.property File

        trace = factory.property Boolean

        autoGeneratedNamesPrefix = factory.property String

        configure {
            files.from project.sourceSets.main.allJava

            trace.set false

            autoGeneratedNamesPrefix.set "${name}.translation-"

            bundlesDir.set project.provider {
                var list = ext.resDirs.get()
                if (list.isEmpty())
                    throw new GradleException("resDirs must contains at least one element, to generate bundles. Or you can set bundlesDir in BundleAutoGen task manually.")
                return new File(list[0].absolutePath, "bundles")
            }
        }

        ext.nmp.configuration {
            bundlesDir.finalizeValue()
            originalFiles.from bundlesDir.get().listFiles(new FilenameFilter() {
                @Override
                boolean accept(File dir, String name) {
                    return name.endsWith(".original.properties")
                }
            })
        }
    }

    @TaskAction
    void processFiles() {
        bundlesDir.finalizeValue()
        trace.finalizeValue()
        files.finalizeValue()
        autoGeneratedNamesPrefix.finalizeValue()

        var entries = new ArrayList<TranslationEntry>()

        var ID = new AtomicLong(0)
        files.each { File file ->
            var result = new ArrayList<TranslationEntry>()
            var blockMatcher = blockPattern.matcher new StringBuilder(file.text)

            while (blockMatcher.find()) {
                var key = blockMatcher.group 1
                if (key == null)
                    key = autoGeneratedNamesPrefix.get() + String.valueOf(ID++)
                var fullMatch = blockMatcher.group()

                var commentStart = fullMatch.indexOf("/*") + 2
                var commentEnd = fullMatch.lastIndexOf("*/")
                var commentContent = fullMatch.substring commentStart, commentEnd

                var translations = new HashMap<String, String>()
                var pairMatcher = pairPattern.matcher(commentContent)
                while (pairMatcher.find()) {
                    var lang = pairMatcher.group 1
                    var translation = pairMatcher.group 2
                    translations[lang] = translation
                }

                result.add new TranslationEntry(key, translations)
            }

            if (trace.get())
                logger.lifecycle("$file.absolutePath: ${result.toString()}")

            entries.addAll(result)
        }

        var bundles = new HashMap<String, HashMap<String, String>>()
        entries.each { TranslationEntry entry ->
            entry.translations.each { String lang, String translation ->
                if (!bundles.containsKey(lang))
                    bundles[lang] = new HashMap<String, String>()

                bundles[lang][entry.key] = translation
            }
        }

        bundles.each { String lang, HashMap<String, String> pairs ->
            var file = new File(bundlesDir.get(), "bundle${lang == "en" ? "" : "_$lang"}.properties")
            var originalFile = new File(bundlesDir.get(), "bundle${lang == "en" ? "" : "_$lang"}.original.properties")

            if (originalFile.exists())
                originalFile.eachLine {String line ->
                    var ind = line.indexOf "="
                    if (ind != -1)
                        pairs[line.substring(0, ind).trim()] = line.substring(ind + 1).trim()
                }

            var text = new StringBuilder()
            pairs.each { String key, String value ->
                text.append "$key = $value\n"
            }

            file.text = text
        }
    }
}

class TranslationEntry {
    public final String key
    public final Map<String, String> translations

    TranslationEntry(String key, Map<String, String> translations) {
        this.key = key
        this.translations = Collections.unmodifiableMap(new HashMap<>(translations))
    }

    @Override
    String toString() {
        return "{" +
                "key='" + key + '\'' +
                ", translations=" + translations +
                '}'
    }
}